### ISSUE TITLE
Integration error 

### ISSUE THREAD

**Issue by BrennanMcDonald** [SEGBK/term-project#16]
`12-05 14:14:43.449 11527-11555/io.github.segbk.termproject E/AndroidRuntime: FATAL EXCEPTION: Thread-4
                                                                             Process: io.github.segbk.termproject, PID: 11527
                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
                                                                                 at librecipe.CookBook$4.run(CookBook.java:213)`

in Cookbook.java on line 158

**Comment by karimsa** [comment]
Can you upload the code you've written to use CookBook?

**Comment by BrennanMcDonald** [comment]
```java
try {
            cookBook = new CookBook();
            cookBook.search("(time > 0) AND (limit by 10)", new ResultsHandler() {
                @Override
                public void onResults(ArrayList<librecipe.Recipe> arrayList) {
                    Log.d("","");
                }
            });
        } catch (Exception ex){

        }
```

**Comment by karimsa** [comment]
You can't use CookBook until it is ready. You should add a ready listener once you instantiate the class:

```java
final CookBook book = new CookBook();
book.onReady(new Runnable() {
  public void run() {
    // here, you can hide your activity indicator and start using cookbook
    cookBook.search("(time > 0) AND (limit by 10)", new ResultsHandler() {
      public void onResults(ArrayList<librecipe.Recipe> arrayList) {
        Log.d("","");
      }
    });
  }
});
```

**Comment by karimsa** [comment]
You should probably also do:

```java
import librecipe.*;
import librecipe.query.*;
```

at the top of your class because you'll be using the objects a lot. Instead of adding the namespace each time.

**Comment by BrennanMcDonald** [comment]
Sounds good, ill try again with this method

**Comment by BrennanMcDonald** [comment]
It fails even before it hits the onReady method. Something is wrong in the constructor of CookBook()

**Comment by karimsa** [comment]
Compile the jar from the latest push, and add an error handler:

```java
book.onError(new EventHandler() {
  public void run(String data) {
    Log.d(data);
  }
});
```

and upload the full stack trace

**Comment by karimsa** [comment]
Sorry, compile again. It rejected my push before.

The event listener methods should be chainable. You should be able to do it all in one line:

```java
final CookBook book = (new CookBook())
  .onReady(...)
  .onError(...);
```

**Comment by BrennanMcDonald** [comment]
Code is not hit as the code is failing at the constructor.

`try {
    final CookBook book = new CookBook();

    book.onError(new EventHandler() {
        public void run(String data) {
            Log.d("COOKBOOKLOG",data);
        }
    });

    book.onReady(new Runnable() {
        public void run() {
            // here, you can hide your activity indicator and start using cookbook
            cookBook.search("(time > 0) AND (limit by 10)", new ResultsHandler() {
                public void onResults(ArrayList<librecipe.Recipe> arrayList) {
                    Log.d("", "");
                }
            });
        }
    });
} catch (Exception ex){}`

**Comment by karimsa** [comment]
The constructor spins off onto another thread though. So those event handlers should be working.

**Comment by karimsa** [comment]
There was only one line in the constructor outside of the other thread. I've removed that now. Does it work now?

**Comment by BrennanMcDonald** [comment]
No, Its hitting onError but the problem is that your error handling is failing.

`for (EventHandler run : that.error) run.run(ex.getStackTrace().toString());`

Line 211 of CookBook.java

This line seems to be the issue.

**Comment by karimsa** [comment]
That should have been fixed with the last commit though, because I've instantiated the the two lists.

Either way, that part should not be erroring out. The data in Firebase is proper.

I've updated again, and this time it will print errors before error handling so we can see the firebase issues.

**Comment by karimsa** [comment]
**Solution**: Android app was missing internet privileges.
